// This file was written by Lucas Saragosa. The code derives from Telltale Games' Engine.
// I do not intend to take credit for it, however; Im the author of this interpretation of 
// the engine and require that if you use this code or library, you give credit to me and
// the amazing Telltale Games.

#pragma once

#include "Container.h"
#include "ResourceBundle.h"//DEPRECATED
#include "DCArray.h"
#include "LanguageRegister.h"
#include "PreloadPackage.h"
#include "HandleObjectInfo.h"
#include "SArray.h"
#include "TRect.h"
#include "DCArray.h"
#include "ObjectSpaceIntrinsics.h"
#include "SoundData.h"
#include "BlendGraph.h"
#include "Set.h"
#include "List.h"
#include "Deque.h"
#include "D3DMesh.h"
#include "LightProbeData.h"
#include "SoundEventBankMap.h"
#include "EventStorage.h"
#include "Rules.h"
#include "Map.h"
#include "PropertySet.h"
#include "Rect.h"
#include "TRange.h"
#include "AnimOrChore.h"
#include "ParticleSprite.h"
#include "T3OverlayData.h"
#include "LanguageDB.h"
#include "StyleGuide.h"
#include "Chore.h"
#include "Animation.h"
#include "Skeleton.h"
#include "ActorAgentMapper.h"
#include "WalkBoxes.h"
#include "SoundFootsteps.h"
#include "Font.h"
#include "AgentMap.h"
#include "SoundBusSystem.h"
#include "AssetCollection.h"
#include "InputMapper.h"
#include "Dialog.h"
#include "TransitionMap.h"
#include "ToolProps.h"
#include "Scene.h"
#include "SoundAmbience.h"
#include "EnlightenData.h"
#include "KeyframedValue.h"
#include "SoundReverbDefinition.h"
#include "AnimatedValueInterface.h"
#include "T3Texture.h"
#include "LocalizationRegistry.h"
#include "LanguageLookupMap.h"
#include "DlgSystemSettings.h"
#include "LanguageDatabase.h"
#include "PhonemeTable.h"
#include "Procedural.h"
#include "LocomotionDB.h"
#include "ParticleProperties.h"